from __future__ import annotations

from matplotlib import cm

DEFAULT_ROOT_PATH = "/Users/k/Documents/skin_data/20260407"
DEFAULT_MEDICINE_COUNT = 1
MAX_MEDICINES = 5
METADATA_FILENAME = ".skin_analysis_metadata.json"

DATA_COL = "pF - Plot 0"
DT_SEC = 0.1
DEFAULT_BASELINE_DURATION_SEC = 20.0
DEFAULT_DRUG_APPLY_TIME_SEC = 25.0
DEFAULT_DRUG_APPLY_TOLERANCE_SEC = 5.0
INITIAL_BASELINE_POINTS = int(round(DEFAULT_BASELINE_DURATION_SEC / DT_SEC))
PBS_BASELINE_PRE_ROLL_POINTS = 200
DROP_SIGMA_THRESHOLD = 3.0
LEGACY_DROP_SEARCH_POINTS = 500
DEFAULT_BASELINE_WARNING_THRESHOLD_PCT = 2.0
OUTLIER_MIN_GROUP_N = 5
OUTLIER_MODIFIED_Z_THRESHOLD = 3.5
DIXON_Q_EXCLUSION_METHOD = "dixon_q"
DIXON_Q_ALPHA = 0.05
DIXON_Q_CRITICAL_VALUES = {
    3: 0.970,
    4: 0.829,
    5: 0.710,
    6: 0.625,
    7: 0.568,
    8: 0.526,
    9: 0.493,
    10: 0.466,
}
BASELINE_TAIL_POINTS = 20
BASELINE_RISE_ROLLING_POINTS = 5
BASELINE_RISE_MIN_RUN = 10
COLOR_PALETTE = tuple(cm.tab10.colors)
LINE_STYLE_CYCLE = ("-", "--", "-.", ":")
